---
- name: Common tasks FTW
  hosts: all
  become: yes
  pre_tasks:
    - name: Set hostname
      hostname: name={{inventory_hostname}}

- name: Base apps service
  hosts: base
  become: yes
  roles:
    - { role: flask, tags: flask }
    - { role: img-panda, tags: img-panda }
    - { role: smart-panda, tags: smart-panda }
